// Dados das conversas entre os personagens
const chats = {
    // Conversa entre Júlia e Henrique
    Julia_Henrique: {
        name: "Conversa – Júlia & Henrique",
        info: "Esta conversa está disponível apenas no celular da Júlia.",
        start: "01:32 | Sexta-feira, 14 de janeiro",
        end: "03:14",
        messages: [
            { sender: "Julia", text: "a gente precisa conversar", time: "01:32" },
            { sender: "Henrique", text: "nossa", time: "01:33" },
            { sender: "Henrique", text: "lá vem", time: "01:33" },
            { sender: "Julia", text: "tô falando sério", time: "01:33" },
            { sender: "Julia", text: "eu sei o que você tá fazendo com a Camila", time: "01:33" },
            { sender: "Henrique", text: "kkkkk", time: "01:34" },
            { sender: "Henrique", text: "e o que seria?", time: "01:34" },
            { sender: "Julia", text: "as fotos", time: "01:34" },
            { sender: "Julia", text: "as ameaças", time: "01:34" },
            { sender: "Julia", text: "você não tem o direito de fazer isso", time: "01:34" },
            { sender: "Henrique", text: "não tô ameaçando ninguém", time: "01:35" },
            { sender: "Henrique", text: "só guardei o que é meu", time: "01:35" },
            { sender: "Julia", text: "ELA NÃO AUTORIZOU", time: "01:35" },
            { sender: "Julia", text: "isso é crime, Henrique", time: "01:35" },
            { sender: "Henrique", text: "crime é trair e depois bancar a vítima", time: "01:36" },
            { sender: "Henrique", text: "ela tá colhendo o que plantou", time: "01:36" },
            { sender: "Julia", text: "você tem noção do quanto isso é doentio?", time: "01:36" },
            { sender: "Julia", text: "ela tá em pânico, não dorme", time: "01:36" },
            { sender: "Julia", text: "e VOCÊ tá achando engraçado?", time: "01:36" },
            { sender: "Henrique", text: "engraçado não", time: "01:37" },
            { sender: "Henrique", text: "justo", time: "01:37" },
            { sender: "Julia", text: "você mudou", time: "01:37" },
            { sender: "Julia", text: "não é mais o mesmo cara que todo mundo admirava", time: "01:37" },
            { sender: "Henrique", text: "ou talvez vocês nunca tenham me conhecido de verdade 🤷‍♂️", time: "01:38" },
            { sender: "Julia", text: "então mostra quem você é", time: "01:38" },
            { sender: "Julia", text: "apaga tudo", time: "01:38" },
            { sender: "Julia", text: "agora", time: "01:38" },
            { sender: "Henrique", text: "não tô com cabeça pra isso agora", time: "01:39" },
            { sender: "Henrique", text: "e sinceramente?", time: "01:39" },
            { sender: "Henrique", text: "não é você que vai me dizer o que fazer", time: "01:39" },
            { sender: "Julia", text: "não sou eu", time: "01:40" },
            { sender: "Julia", text: "mas a polícia pode", time: "01:40" },
            { sender: "Henrique", text: "kkkkkk", time: "01:41" },
            { sender: "Henrique", text: "você vai me denunciar?", time: "01:41" },
            { sender: "Henrique", text: "vai acabar com o fim de semana de todo mundo por causa de DR alheia?", time: "01:41" },
            { sender: "Julia", text: "se for pra proteger alguém, sim", time: "01:41" },
            { sender: "Henrique", text: "você se acha justiceira demais, Júlia", time: "01:42" },
            { sender: "Henrique", text: "vai acabar se ferrando junto", time: "01:42" },
            { sender: "Julia", text: "isso é uma ameaça?", time: "01:43" },
            { sender: "Henrique", text: "interpreta como quiser 😉", time: "01:43" },
            { sender: "Julia", text: "última chance", time: "01:44" },
            { sender: "Julia", text: "você apaga ou eu faço", time: "01:44" },
            { sender: "Henrique", text: "dorme, Júlia", time: "01:44" },
            { sender: "Henrique", text: "tá passando da hora", time: "01:44" },
            { sender: "Julia", text: "não acredito que você tá mesmo indo por esse caminho", time: "03:14" },
            { sender: "Julia", text: "me avisa quando tiver um pingo de vergonha", time: "03:14" }
        ]
    },
    
    // Conversa entre Camila e Júlia
    Camila_Julia: {
        name: "Conversa – Camila & Júlia",
        info: "Esta conversa está disponível apenas no celular da Camila.",
        start: "22:09 | Quarta-feira, 12 de janeiro",
        end: "22:18",
        messages: [
            { sender: "Camila", text: "amiga, tá confirmada a casa?", time: "22:09" },
            { sender: "Julia", text: "simmm", time: "22:10" },
            { sender: "Julia", text: "Diego mandou o comprovante agora", time: "22:10" },
            { sender: "Julia", text: "Arraial do Cabo, aqui vamos nós 🌊✨", time: "22:10" },
            { sender: "Camila", text: "...", time: "22:10" },
            { sender: "Julia", text: "o que foi?", time: "22:11" },
            { sender: "Julia", text: "não me diga que vai desistir", time: "22:11" },
            { sender: "Camila", text: "não é isso", time: "22:11" },
            { sender: "Camila", text: "só… não sei se tô pronta pra passar 3 dias na mesma casa que ele", time: "22:11" },
            { sender: "Julia", text: "o Henrique?", time: "22:12" },
            { sender: "Julia", text: "mas a galera toda vai estar lá", time: "22:12" },
            { sender: "Julia", text: "é só ignorar", time: "22:12" },
            { sender: "Camila", text: "você sabe que não é tão simples", time: "22:12" },
            { sender: "Camila", text: "ele tá me fazendo ameaças, Júlia", time: "22:12" },
            { sender: "Camila", text: "discretas, mas reais", time: "22:12" },
            { sender: "Julia", text: "como assim???", time: "22:13" },
            { sender: "Julia", text: "ele falou algo?", time: "22:13" },
            { sender: "Camila", text: "ele disse que \"ainda tem lembranças\"", time: "22:13" },
            { sender: "Camila", text: "e que talvez \"alguém precise ver quem você realmente é\"", time: "22:13" },
            { sender: "Julia", text: "MEU DEUS", time: "22:14" },
            { sender: "Julia", text: "ele tá falando das fotos?", time: "22:14" },
            { sender: "Camila", text: "eu acho que sim", time: "22:14" },
            { sender: "Camila", text: "e se ele postar?", time: "22:14" },
            { sender: "Camila", text: "se ele manda pra alguém?", time: "22:14" },
            { sender: "Julia", text: "isso é MUITO grave", time: "22:15" },
            { sender: "Julia", text: "você devia denunciar", time: "22:15" },
            { sender: "Camila", text: "e dizer o quê?", time: "22:15" },
            { sender: "Camila", text: "que confiei em alguém que virou um psicopata?", time: "22:15" },
            { sender: "Julia", text: "você não tá sozinha", time: "22:16" },
            { sender: "Julia", text: "eu tô aqui", time: "22:16" },
            { sender: "Julia", text: "e se ele fizer QUALQUER coisa, ele vai se ferrar", time: "22:16" },
            { sender: "Camila", text: "promete?", time: "22:16" },
            { sender: "Julia", text: "por tudo", time: "22:16" },
            { sender: "Julia", text: "ninguém vai passar por isso calada", time: "22:16" },
            { sender: "Julia", text: "não mais", time: "22:16" },
            { sender: "Camila", text: "obrigada", time: "22:17" },
            { sender: "Camila", text: "só me promete que não vai contar pros outros", time: "22:17" },
            { sender: "Julia", text: "só se você deixar", time: "22:17" },
            { sender: "Julia", text: "mas... se algo acontecer, eu juro que vou fazer o que for preciso", time: "22:17" },
            { sender: "Camila", text: "vou tentar ser forte", time: "22:18" },
            { sender: "Camila", text: "só queria que essa viagem fosse leve, sabe?", time: "22:18" },
            { sender: "Julia", text: "vai ser", time: "22:18" },
            { sender: "Julia", text: "se ele mexer com você, ele vai sair de lá sozinho", time: "22:18" }
        ]
    },

    // Conversa entre Camila e Lucas
    Camila_Lucas: {
        name: "Conversa – Camila & Lucas",
        info: "Esta conversa está disponível apenas no celular da Camila.",
        start: "16:11 | Sexta, 14 de janeiro",
        end: "16:20",
        messages: [
            { sender: "Camila", text: "tô cansada", time: "16:11" },
            { sender: "Lucas", text: "tá rolando algo?", time: "16:12" },
            { sender: "Lucas", text: "ou é só vibe de praia errada mesmo?", time: "16:12" },
            { sender: "Camila", text: "é ele de novo", time: "16:13" },
            { sender: "Camila", text: "Henrique", time: "16:13" },
            { sender: "Camila", text: "não sei como ninguém percebe como ele é escroto", time: "16:13" },
            { sender: "Lucas", text: "tem gente que se especializa em enganar geral", time: "16:13" },
            { sender: "Lucas", text: "ele é um mestre nisso", time: "16:13" },
            { sender: "Camila", text: "você ouviu o que ele falou mais cedo?", time: "16:14" },
            { sender: "Camila", text: "aquele comentário nojento na cozinha?", time: "16:14" },
            { sender: "Lucas", text: "ouvi", time: "16:14" },
            { sender: "Lucas", text: "e segurei muito pra não voar nele", time: "16:14" },
            { sender: "Camila", text: "isso não é normal", time: "16:15" },
            { sender: "Camila", text: "não é só uma brincadeira mal colocada", time: "16:15" },
            { sender: "Camila", text: "ele tá me testando", time: "16:15" },
            { sender: "Camila", text: "e pior: se sente impune", time: "16:15" },
            { sender: "Lucas", text: "porque sempre se safou", time: "16:15" },
            { sender: "Lucas", text: "sempre teve quem passasse pano", time: "16:15" },
            { sender: "Camila", text: "eu tô mesmo pensando em denunciar", time: "16:16" },
            { sender: "Lucas", text: "apoio 100%", time: "16:16" },
            { sender: "Lucas", text: "mas posso falar uma coisa?", time: "16:16" },
            { sender: "Camila", text: "pode", time: "16:16" },
            { sender: "Lucas", text: "denúncia às vezes não resolve do jeito que a gente espera", time: "16:17" },
            { sender: "Lucas", text: "tem gente que só entende outra linguagem", time: "16:17" },
            { sender: "Camila", text: "não quero violência, Lucas", time: "16:17" },
            { sender: "Camila", text: "só quero paz", time: "16:17" },
            { sender: "Camila", text: "e que ele me esqueça", time: "16:17" },
            { sender: "Lucas", text: "às vezes a paz vem depois da tempestade", time: "16:18" },
            { sender: "Camila", text: "...", time: "16:18" },
            { sender: "Lucas", text: "relaxa", time: "16:18" },
            { sender: "Lucas", text: "não tô falando de fazer nada", time: "16:18" },
            { sender: "Lucas", text: "só acho que... ele já passou do limite", time: "16:18" },
            { sender: "Camila", text: "obrigada por me ouvir", time: "16:19" },
            { sender: "Camila", text: "de verdade", time: "16:19" },
            { sender: "Lucas", text: "sempre", time: "16:19" },
            { sender: "Lucas", text: "ninguém tem que aguentar isso calado", time: "16:19" },
            { sender: "Camila", text: "se ele fizer algo de novo, vou expor tudo", time: "16:20" },
            { sender: "Camila", text: "não tenho mais medo", time: "16:20" },
            { sender: "Lucas", text: "nem deve", time: "16:20" }
        ]
    },

    // Conversa entre Camila e Diego
    Camila_Diego: {
        name: "Conversa – Camila & Diego",
        info: "Esta conversa está disponível apenas no celular do Diego.",
        start: "01:45 | Sábado, 15 de janeiro",
        end: "01:53",
        messages: [
            { sender: "Camila", text: "tá acordado?", time: "01:45" },
            { sender: "Diego", text: "sim", time: "01:45" },
            { sender: "Diego", text: "tô tentando organizar as fotos da GoPro kkk", time: "01:45" },
            { sender: "Diego", text: "por?", time: "01:45" },
            { sender: "Camila", text: "precisava falar com alguém que ainda parece normal", time: "01:46" },
            { sender: "Diego", text: "👀", time: "01:46" },
            { sender: "Diego", text: "que clima", time: "01:46" },
            { sender: "Diego", text: "fala aí", time: "01:46" },
            { sender: "Camila", text: "você também sente que essa viagem saiu do controle?", time: "01:47" },
            { sender: "Diego", text: "sinto que o grupo tá com umas tensões acumuladas", time: "01:47" },
            { sender: "Diego", text: "mas achei que era coisa passageira", time: "01:47" },
            { sender: "Camila", text: "não é", time: "01:48" },
            { sender: "Camila", text: "tem gente aqui que me faz mal real", time: "01:48" },
            { sender: "Camila", text: "e não é só por causa do passado", time: "01:48" },
            { sender: "Diego", text: "tá falando do Henrique?", time: "01:48" },
            { sender: "Camila", text: "não quero mais dar nome pra isso", time: "01:49" },
            { sender: "Camila", text: "só sei que não quero mais dividir espaço com certas pessoas", time: "01:49" },
            { sender: "Diego", text: "você tá pensando em sair do grupo?", time: "01:49" },
            { sender: "Camila", text: "não oficialmente", time: "01:50" },
            { sender: "Camila", text: "só… me afastar", time: "01:50" },
            { sender: "Camila", text: "parar de forçar a convivência", time: "01:50" },
            { sender: "Camila", text: "chega de sorrir pra gente que não me respeita", time: "01:50" },
            { sender: "Diego", text: "eu entendo", time: "01:51" },
            { sender: "Diego", text: "só espero que isso não seja um adeus de vez", time: "01:51" },
            { sender: "Camila", text: "não é com todo mundo", time: "01:51" },
            { sender: "Camila", text: "mas com quem me faz mal? sim", time: "01:51" },
            { sender: "Camila", text: "é adeus sim", time: "01:51" },
            { sender: "Diego", text: "você precisa de alguma coisa?", time: "01:52" },
            { sender: "Camila", text: "só dormir", time: "01:52" },
            { sender: "Camila", text: "e talvez nunca mais cruzar com certas pessoas na vida", time: "01:52" },
            { sender: "Diego", text: "se precisar de mim", time: "01:53" },
            { sender: "Diego", text: "tô aqui", time: "01:53" },
            { sender: "Camila", text: "valeu, de verdade", time: "01:53" }
        ]
    },

    // Grupo - Arraial Trip
    Grupo_Arraial: {
        name: "Grupo - \"Arraial Trip 🐚🌞\"",
        info: "Esta conversa está disponível no celular de todos os integrantes.",
        start: "18:12 | Sexta, 14 de janeiro",
        end: "18:49",
        messages: [
            { sender: "Diego", text: "Bora churrasco na areia hoje? 🍖🔥", time: "18:12" },
            { sender: "Diego", text: "sol se pondo tá LINDO", time: "18:12" },
            { sender: "Bia", text: "siiimm!", time: "18:13" },
            { sender: "Bia", text: "mas só se tiver farofa de verdade 😤", time: "18:13" },
            { sender: "Lucas", text: "se depender do Henrique vai ter só whey e gelo seco", time: "18:13" },
            { sender: "Henrique", text: "risos forçados", time: "18:14" },
            { sender: "Henrique", text: "me respeita que eu sou gourmet funcional 😎", time: "18:14" },
            { sender: "Julia", text: "alguém viu minha câmera? deixei na mesa e sumiu", time: "18:15" },
            { sender: "Camila", text: "acho que tá no quarto de cima", time: "18:15" },
            { sender: "Camila", text: "vi o Henrique mexendo em umas coisas lá mais cedo 🤷‍♀️", time: "18:15" },
            { sender: "Henrique", text: "oxe", time: "18:16" },
            { sender: "Henrique", text: "já virou CSI agora?", time: "18:16" },
            { sender: "Lucas", text: "quem não deve não treme, irmão", time: "18:17" },
            { sender: "Diego", text: "gente kkkkk vamos focar na carne pelo amor", time: "18:17" },
            { sender: "Bia", text: "vou precisar de uma música tema pra essa tensão", time: "18:18" },
            { sender: "Bia", text: "alô Spotify: \"climão tropical edition\"", time: "18:18" },
            { sender: "Julia", text: "tá tudo bem gente, era só pra saber mesmo", time: "18:19" },
            { sender: "Julia", text: "achei aqui, tava na rede", time: "18:19" },
            { sender: "Camila", text: "🙄", time: "18:20" },
            { sender: "Henrique", text: "tá difícil agradar hoje hein", time: "18:21" },
            { sender: "Henrique", text: "acho que alguém acordou amargo", time: "18:21" },
            { sender: "Camila", text: "não era comigo?", time: "18:21" },
            { sender: "Lucas", text: "🔥🔥🔥", time: "18:22" },
            { sender: "Diego", text: "GENTE", time: "18:22" },
            { sender: "Diego", text: "concentra", time: "18:22" },
            { sender: "Diego", text: "vou sair agora pra comprar carvão e cerveja", time: "18:22" },
            { sender: "Diego", text: "alguém quer algo?", time: "18:22" },
            { sender: "Julia", text: "vinho branco", time: "18:23" },
            { sender: "Julia", text: "pra ver se esse grupo vira adulto em algum momento 🍷", time: "18:23" },
            { sender: "Bia", text: "traz bala", time: "18:23" },
            { sender: "Bia", text: "preciso de açúcar pra aturar vocês", time: "18:23" },
            { sender: "Henrique", text: "eu só queria paz", time: "18:24" },
            { sender: "Henrique", text: "e talvez um pouco de respeito 🥺👉👈", time: "18:24" },
            { sender: "Lucas", text: "paz se constrói", time: "18:25" },
            { sender: "Lucas", text: "com ações", time: "18:25" },
            { sender: "Diego", text: "ok", time: "18:26" },
            { sender: "Diego", text: "vou considerar que vocês só tão com fome mesmo", time: "18:26" }
        ]
    },

    // Conversa entre Bia e Júlia
    Bia_Julia: {
        name: "Conversa – Bia & Júlia",
        info: "Esta conversa está disponível apenas no celular da Júlia.",
        start: "07:02 | Sábado, 15 de janeiro",
        end: "07:08",
        messages: [
            { sender: "Bia", text: "Júlia?", time: "07:02" },
            { sender: "Bia", text: "acordei com um grito… tá tudo bem aí?", time: "07:02" },
            { sender: "Julia", text: "não sei", time: "07:03" },
            { sender: "Julia", text: "tá uma confusão aqui fora", time: "07:03" },
            { sender: "Julia", text: "o Diego saiu correndo pra praia", time: "07:03" },
            { sender: "Bia", text: "Lucas tá no quarto?", time: "07:03" },
            { sender: "Julia", text: "não", time: "07:03" },
            { sender: "Bia", text: "vi ele entrando ontem umas 3 da manhã", time: "07:04" },
            { sender: "Bia", text: "todo molhado", time: "07:04" },
            { sender: "Bia", text: "disfarçou mal", time: "07:04" },
            { sender: "Julia", text: "sério?", time: "07:04" },
            { sender: "Bia", text: "tô falando", time: "07:05" },
            { sender: "Bia", text: "tava estranho", time: "07:05" },
            { sender: "Bia", text: "e quando viu que eu tava acordada, fingiu que foi beber água", time: "07:05" },
            { sender: "Julia", text: "por que não falou nada antes?", time: "07:05" },
            { sender: "Bia", text: "não queria criar mais treta", time: "07:06" },
            { sender: "Bia", text: "mas sei lá", time: "07:06" },
            { sender: "Bia", text: "tô com uma sensação esquisita", time: "07:06" },
            { sender: "Julia", text: "ok", time: "07:07" },
            { sender: "Julia", text: "me encontra na varanda em 5", time: "07:07" },
            { sender: "Julia", text: "traz o celular", time: "07:07" },
            { sender: "Bia", text: "indo", time: "07:08" }
        ]
    }
};

// Mapeamento de quais conversas estão disponíveis em cada celular
const availableChats = {
    Julia: [
        { id: "Julia_Henrique", with: "Henrique" },
        { id: "Bia_Julia", with: "Bia" },
        { id: "Grupo_Arraial", with: "Grupo" }
    ],
    Camila: [
        { id: "Camila_Julia", with: "Julia" },
        { id: "Camila_Lucas", with: "Lucas" },
        { id: "Grupo_Arraial", with: "Grupo" }
    ],
    Henrique: [
        { id: "Grupo_Arraial", with: "Grupo" }
    ],
    Diego: [
        { id: "Camila_Diego", with: "Camila" },
        { id: "Grupo_Arraial", with: "Grupo" }
    ],
    Lucas: [
        { id: "Grupo_Arraial", with: "Grupo" }
    ],
    Beatriz: [
        { id: "Grupo_Arraial", with: "Grupo" }
    ]
}; 